import {
    StyleSheet
} from 'react-native';
import {
    scaleSize,
    setSpText,
    screenW,
    screenH,
} from '../../util/autoSize'
export default StyleSheet.create({
    container:{
        flex:1,
        justifyContent:'center',
        alignItems:'center',
    },
    loginList:{
        height:40,
        width:screenW,
        flexDirection:'row',
        alignItems:'center',
        paddingRight:10,
        paddingLeft:10
    },
    loginText:{
        width:50,
        textAlign:'right',
        fontSize:16,
        color:'#333',
        marginRight:10
    },
    inputStyle:{
       paddingLeft:10,
       paddingRight:10, 
       paddingTop:0,
       paddingBottom:0,
       height:'100%',
       flex:1,
       fontSize:16,
       color:'#000',
       borderLeftWidth:1,
       borderRightWidth:1,
       borderTopWidth:1,
       borderBottomWidth:1,
       borderBottomColor:'#ccc',
       borderLeftColor:'#ccc',
       borderTopColor:'#ccc',
       borderRightColor:'#ccc', 
    },
    btnContainer:{
       marginTop:20,
       width:200,
       height:40,
       backgroundColor:'blue',
       borderRadius:20,
       justifyContent:'center',
        alignItems:'center',
    },
    btnText:{
        fontSize:16,
        color:'#fff',
        lineHeight:40,
    }
})